"""Gate 3 CLI: score a pack's cards against the shipped-pool balance envelopes
and write packs/<Pack>/BALANCE-REPORT.md.

Usage:
    python tools/sim/report.py packs/<Pack>/pack.json [--rebuild-envelopes] [-o OUT.md]
    python tools/sim/report.py --all
    python tools/sim/report.py --self-check          # calibration numbers only

Verdicts:
  ON-CURVE          power inside the rarity envelope's P5-P95
  OVER / UNDER      power outside P95 / P5
  DEGENERATE-RISK   static loop sniff hit, or damage still scaling at the turn cap
  INSUFFICIENT-SIM  <80% of the card's behavior is simulable — needs in-game QA,
                    NOT necessarily a bad card
"""

from __future__ import annotations

import argparse
import json
import sys
from dataclasses import dataclass
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
import gamedata as gd                      # noqa: E402
from sim import dsl, engine, envelopes     # noqa: E402

SIM_THRESHOLD = 0.8
SCALING_FLAG_RATIO = 1.5   # late-window marginal damage >= 1.5x early window


@dataclass
class CardVerdict:
    card: dsl.CardModel
    sim_pct: float
    score: engine.CardScore | None
    envelope: envelopes.Envelope | None
    verdict: str
    band: str
    notes: list[str]
    degeneracy: list[str]


def evaluate_card(card: dsl.CardModel, data: dict) -> CardVerdict:
    sim_pct = card.simulability()
    notes = card.sim_notes()
    degen = dsl.degeneracy_flags(card)
    score = None
    band = "-"
    env = envelopes.envelope_for(card.rarity, data)

    if sim_pct > 0:
        score = engine.score_card(card)
        if score.scaling_ratio >= SCALING_FLAG_RATIO and score.dmg_delta > 0:
            degen.append(f"damage contribution still growing at the turn cap "
                         f"(late/early ratio {score.scaling_ratio:.2f})")

    if degen:
        verdict = "DEGENERATE-RISK"
    elif sim_pct < SIM_THRESHOLD:
        verdict = "INSUFFICIENT-SIM"
    elif score is None or env is None:
        verdict = "INSUFFICIENT-SIM"
    else:
        verdict = env.position(score.power)
    if score is not None and env is not None:
        band = env.band(score.power)
        mapped = envelopes.RARITY_FALLBACK.get(card.rarity, card.rarity)
        if env.rarity != mapped:
            band += f" (vs {env.rarity})"  # tier fallback: too few shipped cards
    return CardVerdict(card, sim_pct, score, env, verdict, band, notes, degen)


def render_report(pack_name: str, verdicts: list[CardVerdict], data: dict) -> str:
    st = data["stats"]
    sc = data["self_check"]
    lines = [
        f"# Balance report — {pack_name}",
        "",
        "Generated by `tools/sim/report.py` (gate 3). Read"
        " `tools/sim/README.md` for what this harness can and cannot see.",
        "",
        "## Calibration state",
        "",
        f"- Reference corpus: {st['fully_simulable']} fully-simulable shipped cards "
        f"({st['coverage_pct']}% of the {st['player_legal_simple_category']} "
        "player-legal action-routed cards).",
        f"- Self-check: {sc['on_curve']}/{sc['sample_size']} seeded-random shipped "
        f"commons land ON-CURVE — {'PASS' if sc['pass'] else 'FAIL (do not trust these verdicts)'}.",
        "",
        "## Envelopes (power score, HP-equivalent, per rarity)",
        "",
        "| Rarity | n | P5 | P25 | P50 | P75 | P95 |",
        "|---|---|---|---|---|---|---|",
    ]
    for rarity in envelopes.ENVELOPE_RARITIES:
        e = data["envelopes"].get(rarity)
        if e:
            lines.append(f"| {rarity} | {e['n']} | {e['p5']:.1f} | {e['p25']:.1f} | "
                         f"{e['p50']:.1f} | {e['p75']:.1f} | {e['p95']:.1f} |")
    lines += ["", "## Cards", ""]
    lines.append("| Card | Rarity | Cost | Sim% | Power | Δdmg | Δsustain | Δcards | Band | Verdict |")
    lines.append("|---|---|---|---|---|---|---|---|---|---|")
    for v in verdicts:
        c = v.card
        if v.score:
            p, d, s_, cd = (f"{v.score.power:.1f}", f"{v.score.dmg_delta:.1f}",
                            f"{v.score.sustain_delta:.1f}", f"{v.score.cards_delta:.1f}")
        else:
            p = d = s_ = cd = "-"
        lines.append(f"| {c.name} | {c.rarity} | {c.cost}{'+'+str(c.life_cost)+'L' if c.life_cost else ''} "
                     f"| {v.sim_pct * 100:.0f}% | {p} | {d} | {s_} | {cd} | {v.band} | **{v.verdict}** |")
    lines.append("")
    for v in verdicts:
        if not (v.notes or v.degeneracy):
            continue
        lines.append(f"### {v.card.name}")
        lines.append("")
        for flag in v.degeneracy:
            lines.append(f"- DEGENERACY: {flag}")
        for note in v.notes:
            lines.append(f"- not simulated: {note}")
        lines.append("")
    lines += [
        "## How to read this",
        "",
        "- **Power** = mean HP-equivalent swing vs the 10-card baseline deck over an "
        "8-turn scripted combat, averaged across 3 enemy profiles x 3 seeds "
        "(delta vs the same deck without the card — energy opportunity cost is "
        "priced in automatically).",
        "- **ON-CURVE** means inside the shipped pool's P5-P95 for that rarity; the "
        "Band column shows where. P25-P75 is the comfortable middle.",
        "- **INSUFFICIENT-SIM** is not a balance judgement. It means the card's "
        "behavior is mostly outside the simulable DSL subset; it needs gate-4 "
        "in-game QA.",
        "- **DEGENERATE-RISK** flags unbounded replay/copy/conjure loops or damage "
        "still accelerating at the 16-turn cap. Verify by hand.",
        "",
    ]
    return "\n".join(lines)


def run_pack(pack_path: Path, data: dict, out: Path | None) -> int:
    manifest = json.loads(pack_path.read_text(encoding="utf-8"))
    pack_name = manifest.get("pack", pack_path.parent.name)
    verdicts = []
    for c in manifest.get("cards", []):
        card = dsl.card_from_pack_json(c)
        verdicts.append(evaluate_card(card, data))
    text = render_report(pack_name, verdicts, data)
    out_path = out or (pack_path.parent / "BALANCE-REPORT.md")
    out_path.write_text(text, encoding="utf-8")
    flagged = [v for v in verdicts if v.verdict in ("OVER", "DEGENERATE-RISK")]
    print(f"== {pack_name}: {len(verdicts)} cards -> {out_path}")
    for v in verdicts:
        extra = f" power={v.score.power:.1f} band={v.band}" if v.score else ""
        print(f"  {v.verdict:16s} {v.card.name} (sim {v.sim_pct*100:.0f}%{extra})")
    return 1 if flagged else 0


def print_self_check(data: dict) -> None:
    st, sc = data["stats"], data["self_check"]
    print(f"corpus: {st['fully_simulable']}/{st['player_legal_simple_category']} "
          f"player-legal action-routed cards fully simulable ({st['coverage_pct']}%)")
    print(f"self-check: {sc['on_curve']}/{sc['sample_size']} shipped commons ON-CURVE "
          f"-> {'PASS' if sc['pass'] else 'FAIL'}")
    for r in data["self_check"]["results"]:
        print(f"  {r['verdict']:9s} {r['name']} (power {r['power']})")


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("pack", nargs="?", help="packs/<Pack>/pack.json")
    ap.add_argument("--all", action="store_true")
    ap.add_argument("--self-check", action="store_true")
    ap.add_argument("--rebuild-envelopes", action="store_true")
    ap.add_argument("-o", "--out", type=Path, help="report output path override")
    args = ap.parse_args(argv)

    data = envelopes.build_envelopes(rebuild=args.rebuild_envelopes)
    if args.self_check:
        print_self_check(data)
        return 0 if data["self_check"]["pass"] else 1

    if args.all:
        paths = sorted(gd.PACKS_DIR.glob("*/pack.json"))
        if not paths:
            print("no packs/*/pack.json found")
            return 0
    elif args.pack:
        paths = [Path(args.pack)]
    else:
        ap.error("give a pack.json path, --all, or --self-check")

    rc = 0
    for p in paths:
        rc |= run_pack(p, data, args.out if len(paths) == 1 else None)
    return rc


if __name__ == "__main__":
    sys.exit(main())
