// Clean-spelled public enum mirrors of the game's content enums (SPEC.md 4.2).
// The game's own enums contain canonical typos that are API surface for raw data
// packs (CardRariry, Suffix.Phyisical); the C# API exposes corrected spellings and
// maps to the game's members internally (CleanEnums.cs). Member ORDER and every
// non-typo'd NAME mirror the game enums 1:1 (verified against decompiled/).

namespace DawnKit
{
    /// <summary>Mirror of Card.CardType.</summary>
    public enum CardType
    {
        Melee,
        Magic,
        Ranged,
        Utility,
        Divine,
        Move,
        Corruption,
        Monster,
    }

    /// <summary>Mirror of Card.CardCategory.</summary>
    public enum CardCategory
    {
        Action,
        Item,
        Artifact,
        Conjuration,
        Enchantment,
        BasicAttack,
        Summon,
        Performance,
        Form,
        Hymn,
        Revelation,
        Affix,
        Attunement,
        Equipment,
        Code,
        Ingredient,
        Path,
        Location,
        Offering,
        Mantra,
        Adaptation,
    }

    /// <summary>Mirror of Card.Suffix. Physical maps to the game's typo'd member 'Phyisical'.</summary>
    public enum Suffix
    {
        None,
        Fire,
        Frost,
        Lightning,
        Physical,
        Ebb,
        Flow,
        Infernal,
        Companion,
        Junk,
    }

    /// <summary>Mirror of Card.CardRariry (the game's type name is typo'd; members are clean).</summary>
    public enum Rarity
    {
        Common,
        Uncommon,
        Rare,
        Legendary,
        Monster,
        Epic,
        Mythic,
        Ultra,
    }

    /// <summary>Mirror of AssetManager.CardExpansions (native members only; mod sets come from Sets.Register).</summary>
    public enum Expansion
    {
        None,
        Core,
        Metaprogress,
        Metamorphosis,
        Extended,
        Infinitum,
        Catalyst,
        Eclypse,
        Synthesis,
    }

    /// <summary>Mirror of EventHandler.GameTriggers.</summary>
    public enum Trigger
    {
        None,
        PlayAction,
        Pause,
        GainEnergy,
        SpendEnergy,
        DealtDamage,
        CalculateIncomingDamage,
        GainHealth,
        GainStatusStack,
        LoseStatusStack,
        Shuffle,
        Kill,
        Draw,
        Bury,
        Discard,
        Remove,
        Conjure,
        Return,
        StartCombat,
        StartPhase,
        EnergyPhase,
        DrawPhase,
        PlayPhase,
        DiscardPhase,
        EndTurnPhase,
        EnemyPhase,
        VictoryPhase,
        NoCombat,
        GainGold,
        GainFood,
        GainRestingHealing,
        RollTreasure,
        CalculateGoldCost,
        CalculateOutgoingDamage,
        CalculateCardCost,
        ResolveDamage,
        AcquireCard,
        RemoveCard,
        ActivateWeapon,
        EnemyPlaysAction,
        GainUniqueStatus,
        EncounterOpportunity,
        UpgradeAction,
        ImbueEnchantment,
        EndAction,
        Rewards,
        EnterCombat,
        VisitCampsite,
        Death,
        PickEvent,
        CriticalHit,
        TakeStatusDamage,
        AfterTakenDamage,
        EncounterShrine,
        Reshuffle,
        Shout,
        CompanionPlays,
        EndRun,
        FinalVictory,
        FinalDefeat,
        Highscore,
        ReachCanto,
        Perform,
        Playerdeath,
        Shapechange,
        Gainsouls,
        Deepwound,
        FinishPerformance,
        CardReward,
        EndDamage,
        AfterHealing,
        EnemyEndsAction,
        Reveal,
        SpendCharge,
        InflictStatus,
        InflictUniqueStatus,
        InflictDamage,
        QueueAction,
        InflictStatusDamage,
        ResolveDamageTaken,
        SummonClone,
        ChangeTide,
        AttuneTrigger,
        ShuffleCard,
        EnterStance,
        GainEnchantment,
        IncomingDamage,
        LoseGold,
        AddCardToEnemyDeck,
        Interrupt,
        ResetCard,
        PostAction,
        StartGame,
        BelowZeroHealth,
        UpdateAreaSpecial,
        Defile,
        Foretell,
        ChangeMaxHealth,
        LoseStatus,
        GainAffliction,
        MutateCard,
        Reaping,
        EnemyGainsStatus,
        PlayerBelowZeroHealth,
        GainFaith,
        FinishHymn,
        Adapt,
        ScavengeAdd,
        ScavengeDraw,
        Scavenge,
        AddCardToScrap,
        AddCompanionCard,
        ActivateEquipment,
    }
}
